stages:
  - build
  - deploy

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Successfull to build the App"
  only:
    - development
  
artifacts:
    paths:
    - build/

deploy:
  stage: deploy
  image: alpine
  script: 
    - echo Deployed
  only:
    - development