stages:
  - build
  - deploy

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"

deploy_production:
  stage: deploy
  script:
      - echo "Deploying to server"
      - cp -rv build/* /var/www/html/<destination_folder>/
      - echo "Deployed"
  environment:
      name: production
      url: <your deployment url>
  only:
      - development