stages:
  - build
  # - deploy

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Successfull to build the App"
  only:
    - development
    # - production
  
# artifacts:
#     paths:
#     - build/

# deploy:
#   stage: deploy
#   image: alpine
#   script: 
#     - apk add --no-cache rsync openssh
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
#     - chmod 600 ~/.ssh/id_dsa
#     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#     - rsync -ravO build/ ssh root@172.104.40.167:/var/www/www.investx.id/
#   only:
#     - production