deploy_staging:
  image: node:lts
  cache:
    paths:
      - node_modules/
 
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass rsync

  only:
    refs:
      - development

  stage: deploy
  environment: Production
  script:
    - npm install
    - npm run build
    - cd build/
    - ls
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . $USER_NAME@$SERVER_IP:/var/www/www.investx.id/build/


build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind

  before_script:
    # Log in to Google Container Registry
    - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://asia.gcr.io
    - rm .env
    - echo $APP_ENV > .env
  script:
    - docker build --cache-from "${DOCKER_IMAGE_TAG}" -t "${DOCKER_IMAGE_TAG}" .
    - docker push ${DOCKER_IMAGE_TAG}
  only:
    - master
