stages:
    - build
    - deploy
build:
    stage: build
    tags: 
        - <tag you provided while registering the token>
        - <second tag>
    script:
        - echo "Building deploy package"
        - npm i
        - npm run build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build

deploy_production:
    stage: deploy
    tags: 
      - <tag you provided while registering the token>
      - <second tag>
    script:
        - echo "Deploying to server"
        - cp -rv build/* /var/www/www.investx.id/build
        - echo "Deployed"
    environment:
        name: production
        url: <your deployment url>
    only:
        - development