# stages:
#     - build
#     - deploy
# build:
#     stage: build
#     # tags: 
#     #     - <tag you provided while registering the token>
#     #     - <second tag>
#     script:
#         - echo "Building deploy package"
#         - npm i
#         - npm run build
#         - echo "Build successful"
#     artifacts:
#         expire_in: 1 hour
#         paths:
#             - build

# deploy_production:
#     stage: deploy
#     # tags: 
#     #   - <tag you provided while registering the token>
#     #   - <second tag>
#     script:
#         - echo "Deploying to server"
#         - cp -rv build/* /var/www/www.investx.id/build
#         - echo "Deployed"
#     environment:
#         name: production
#         url: <your deployment url>
#     only:
#         - development


# stages:
#   - build
#   - deploy

# build_react:
#   image: node:alpine
#   stage: build

#   script:
#     - echo "====== Install dependencied ======"
#     - npm i
#     - echo "====== Build react APP ======"
#     - npm run build

#   artifacts:
#     name: panel-build
#     expire_in: 1 hour
#     paths:
#       - build

# deploy_react:
#   image: alpine
#   stage: deploy
#   script:
#     - echo 'test kemal'
#     - ssh $TARGET_SERVER_USER_HOST
#     - ssh $PASSWORD_USER
#     - echo 'test kemal END'
    # - echo "====== Deploy to production server ======"
    # - apk update && apk upgrade
    # - apk add openssh bash rsync
    # - echo "====== Add target servers secret key ======"
    # - mkdir ~/.ssh
    # - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    # - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    # - echo "====== Test ssh connection ======"
    # - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T "$TARGET_SERVER_USER_HOST"
    # - echo "====== Install rsync on remote server ======"
    # - ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null  "$TARGET_SERVER_USER_HOST" 'sudo apt-get install rsync -y'
    # - echo "====== Sync local and remote directory ======"
    # # Ending "/" in string "./build/" is important!
    # - rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete ./build/ "$TARGET_SERVER_USER_HOST:$TARGET_SERVER_PATH"
  # only:
  # - development


  image: node:v14.4.0

  stages: 
    - deploy
  
  deploy:
    script:
    - echo 'test kemal'
    - ssh $TARGET_SERVER_USER_HOST
    - $PASSWORD_USER
    - echo 'test kemal END'
    only:
      - development
